import React, { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { getCurrentOrgId } from '@/lib/orgContext';
import { useAuth } from '@/contexts/AuthContext';
import { getDashboardData } from '@/services/dashboardService';
import { Award, TrendingUp, Clock, Zap, Download } from 'lucide-react';

interface ReportCard {
  avgHealthScore: number;
  avgLeaveApprovalDays: number;
  aiAdoptionRate: number;
  velocityTrend: number; // % change
  projectsCompleted: number;
  tasksApproved: number;
  month: string;
}

export const ManagerReportCard: React.FC = () => {
  const { user } = useAuth();
  const [report, setReport] = useState<ReportCard | null>(null);
  const [loading, setLoading] = useState(true);

  const firstName = user?.user_metadata?.full_name?.split(' ')[0] || 'Manager';

  useEffect(() => {
    const load = async () => {
      const orgId = getCurrentOrgId();
      if (!orgId) return;
      try {
        const monthAgo = new Date();
        monthAgo.setDate(monthAgo.getDate() - 30);
        const twoMonthsAgo = new Date();
        twoMonthsAgo.setDate(twoMonthsAgo.getDate() - 60);

        const [projectsRes, leavesRes, suggestionsRes, tasksThisMonth, tasksPrevMonth] = await Promise.all([
          supabase.from('projects').select('id, status').eq('organization_id', orgId).eq('status', 'completed').gte('updated_at', monthAgo.toISOString()),
          supabase.from('leave_requests').select('created_at, updated_at, status').eq('organization_id', orgId).neq('status', 'pending').gte('created_at', monthAgo.toISOString()),
          supabase.from('ai_task_suggestions').select('status').gte('created_at', monthAgo.toISOString()),
          supabase.from('tasks').select('id').eq('status', 'completed').gte('updated_at', monthAgo.toISOString()),
          supabase.from('tasks').select('id').eq('status', 'completed').gte('updated_at', twoMonthsAgo.toISOString()).lt('updated_at', monthAgo.toISOString()),
        ]);

        // Avg leave approval time
        const approvedLeaves = (leavesRes.data || []).filter(l => l.status !== 'pending');
        const avgApprovalDays = approvedLeaves.length > 0
          ? Math.round(approvedLeaves.reduce((s, l) => {
              const diff = (new Date(l.updated_at).getTime() - new Date(l.created_at).getTime()) / 86400000;
              return s + diff;
            }, 0) / approvedLeaves.length * 10) / 10
          : 0;

        // AI adoption rate
        const suggestions = suggestionsRes.data || [];
        const approved = suggestions.filter(s => s.status === 'approved').length;
        const aiAdoption = suggestions.length > 0 ? Math.round((approved / suggestions.length) * 100) : 0;

        // Velocity trend
        const thisMonth = tasksThisMonth.data?.length || 0;
        const prevMonth = tasksPrevMonth.data?.length || 0;
        const velocityTrend = prevMonth > 0 ? Math.round(((thisMonth - prevMonth) / prevMonth) * 100) : 0;

        // Health score from dashboard
        const dash = await getDashboardData() as any;
        const utilization = parseInt(dash?.kpis?.find((k: any) => k.label === 'TEAM UTILIZATION')?.value?.replace('%', '') || '0');
        const atRisk = dash?.kpis?.find((k: any) => k.label === 'PROJECTS AT RISK')?.value || 0;
        const healthScore = Math.max(20, Math.min(100, utilization - (Number(atRisk) * 15)));

        setReport({
          avgHealthScore: healthScore,
          avgLeaveApprovalDays: avgApprovalDays,
          aiAdoptionRate: aiAdoption,
          velocityTrend,
          projectsCompleted: projectsRes.data?.length || 0,
          tasksApproved: approved,
          month: new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }),
        });
      } catch (e) {
        console.error('ManagerReportCard error:', e);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  const handleDownload = () => {
    if (!report) return;
    const text = `Manager Report Card — ${report.month}
Manager: ${firstName}

Project Health Score: ${report.avgHealthScore}/100
Leave Approval Time: ${report.avgLeaveApprovalDays} days avg
AI Adoption Rate: ${report.aiAdoptionRate}%
Team Velocity Trend: ${report.velocityTrend > 0 ? '+' : ''}${report.velocityTrend}% vs last month
Projects Completed: ${report.projectsCompleted}
AI Suggestions Approved: ${report.tasksApproved}

Generated by Velocity AI`;
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `manager-report-${report.month.toLowerCase().replace(' ', '-')}.txt`;
    a.click();
  };

  if (loading) return null;
  if (!report) return null;

  const grade = report.avgHealthScore >= 80 ? 'A' : report.avgHealthScore >= 65 ? 'B' : report.avgHealthScore >= 50 ? 'C' : 'D';
  const gradeColor = { A: 'text-green-600 bg-green-50', B: 'text-blue-600 bg-blue-50', C: 'text-amber-600 bg-amber-50', D: 'text-red-600 bg-red-50' }[grade];

  return (
    <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
      <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100 bg-gradient-to-r from-gray-50 to-white">
        <div className="flex items-center gap-2">
          <Award className="w-4 h-4 text-primary" />
          <h3 className="text-sm font-medium text-gray-900">{firstName}'s Report Card</h3>
          <span className="text-xs text-gray-400">— {report.month}</span>
        </div>
        <div className="flex items-center gap-2">
          <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${gradeColor}`}>{grade}</div>
          <button onClick={handleDownload} className="text-gray-400 hover:text-gray-600"><Download className="w-4 h-4" /></button>
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 gap-4 p-5">
        {[
          { icon: <TrendingUp className="w-4 h-4 text-primary" />, value: `${report.avgHealthScore}`, label: 'Health Score', sub: 'out of 100' },
          { icon: <Clock className="w-4 h-4 text-amber-500" />, value: `${report.avgLeaveApprovalDays}d`, label: 'Leave Approval', sub: 'average response' },
          { icon: <Zap className="w-4 h-4 text-violet-500" />, value: `${report.aiAdoptionRate}%`, label: 'AI Adoption', sub: 'suggestions approved' },
          { icon: <TrendingUp className="w-4 h-4 text-green-500" />, value: `${report.velocityTrend > 0 ? '+' : ''}${report.velocityTrend}%`, label: 'Velocity Trend', sub: 'vs last month' },
          { icon: <Award className="w-4 h-4 text-blue-500" />, value: `${report.projectsCompleted}`, label: 'Projects Done', sub: 'this month' },
          { icon: <Zap className="w-4 h-4 text-primary" />, value: `${report.tasksApproved}`, label: 'Tasks Approved', sub: 'from AI suggestions' },
        ].map(({ icon, value, label, sub }) => (
          <div key={label} className="bg-gray-50 rounded-xl p-4">
            <div className="flex items-center gap-2 mb-2">{icon}<span className="text-xs text-gray-500">{label}</span></div>
            <p className="text-2xl font-light text-gray-900">{value}</p>
            <p className="text-xs text-gray-400 mt-0.5">{sub}</p>
          </div>
        ))}
      </div>
    </div>
  );
};
